telegram:
  token: "7323085730:AAFyarRa7duoPVySNNOxVhQUd94rQLepQpc"
  admin_users:
    - 123456789  # 管理员用户ID

database:
  path: "website_templates.db"

collector:
  timeout: 120  # 修改为120秒 (2分钟)
  max_retries: 3

similarity:
  threshold: 0.4

cleanup:
  days: 30 